## FIRST, AN R SCRIPT TO GENERATE THE COMBINATION NAMES OF THE PAIRWISE COMPARISONS BETWEEN TIMEPOINTS.

# Rscript arg1: $sampleandaccessionlists directory containing all the sample and accession lists for looping arg2: $results_dir dir of output file arg3: $timepoint_name_list list of the names of each timepoint arg4: $list_of_timepoint_comparisons_final list of the names of each pairwise comparison between timepoints as generated by the previous script, generatingpairwisecomparisonlist.R arg5: $JUM_diff_dir directory of the JUM_diff folder as generated by JUM_A_multi_2.sh

print(commandArgs())

args = commandArgs(trailingOnly=TRUE)

print(args)

print(paste("number of arguments: ", length(args), sep = ""))

# test if there are 5 arguments: if not, return an error
if (length(args)!=5) {
  stop("check the amount of arguments you have. should have specified 3", call.=FALSE)
}

# NOTE: replicate number needs to be changed depending on if BM or AT derived cells. i hard-set this cause i dont think we gona do AT cells anyways.

list_of_timepoint_comparisons_final <- read.delim(file = args[4], row.names = NULL, header = FALSE, stringsAsFactors = FALSE)

for (comparison in list_of_timepoint_comparisons_final[, 1])

{

temp_exptdesign_table <- data.frame(matrix(nrow=6, ncol=2), row.names = NULL)
colnames(temp_exptdesign_table) <- c("replicatename", "condition")

temp_exptdesign_table[1:3, 2] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\1")
temp_exptdesign_table[1, 1] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\1_r1")
temp_exptdesign_table[2, 1] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\1_r2")
temp_exptdesign_table[3, 1] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\1_r3")

temp_exptdesign_table[4:6, 2] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\2")
temp_exptdesign_table[4, 1] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\2_r1")
temp_exptdesign_table[5, 1] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\2_r2")
temp_exptdesign_table[6, 1] <- gsub(x = comparison, pattern = "(.*)_vs_(.*)", replacement = "\\2_r3")

# sort alphabetically

temp_exptdesign_table <- temp_exptdesign_table[order(temp_exptdesign_table$replicatename), ]

write.table(x = temp_exptdesign_table, file = paste(args[5], comparison, "/experiment_design.txt", sep = ""), quote = FALSE, col.names = TRUE, row.names = FALSE, sep = "\t")

}

q(save = "no")
